name: Ngrok
version: 1.0.0
slug: ngrok
description: Ngrok tunnel client with fixed URL support
url: https://github.com/Chriser001/ha-addon-ngrok
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
options:
  auth_token: ""
  upstream_url: "http://host.docker.internal:8123"
  url_param: ""
schema:
  auth_token: str
  upstream_url: str
  url_param: str
ports:
  4040/tcp: 4040
